# Generated by Django 4.2.2 on 2023-07-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typetitle', models.CharField(max_length=50, verbose_name='Film/Dizi Türü')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=50, verbose_name='Fim/Dizi Adı')),
                ('image', models.ImageField(upload_to='Film/Dizi', verbose_name='Film/Dizi Resmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='film Kartı')),
                ('movietype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.movietype', verbose_name='Film/Dizi Türü')),
            ],
        ),
    ]
