# Generated by Django 4.2.2 on 2023-07-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_rename_movietype_moviecard_typetitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='moviecard',
            name='typeTitle',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MovieCard',
        ),
        migrations.DeleteModel(
            name='MovieType',
        ),
    ]
