# Generated by Django 4.2.2 on 2023-07-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appMy', '0006_remove_moviecard_category_remove_moviecard_typetitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catetitle', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=50, verbose_name='Fİlm/Dizi Adı')),
                ('image', models.ImageField(upload_to='Fİlm/Dizi Adı', verbose_name='Film/Dizi Resmi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori Adı')),
                ('movietype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.movietype', verbose_name='Film/Dizi Türü')),
            ],
        ),
    ]
