# Generated by Django 4.2.2 on 2023-07-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieType',
            new_name='Type',
        ),
    ]
