# Generated by Django 4.2.2 on 2023-07-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='typetitle',
        ),
    ]
