# Generated by Django 4.2.2 on 2023-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_rename_type_type_typetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='typetitle',
            new_name='type',
        ),
    ]
