# Generated by Django 4.2.2 on 2023-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_rename_typetitle_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='listadd',
            field=models.BooleanField(default=False, null=True, verbose_name='List-like'),
        ),
    ]
