# Generated by Django 4.2.2 on 2023-07-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0015_card_listadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='listadd',
        ),
        migrations.AddField(
            model_name='card',
            name='listLike',
            field=models.BooleanField(default=False, null=True, verbose_name='Listem'),
        ),
    ]
