# Generated by Django 4.2.2 on 2023-07-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_userinfo_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='listadd',
            field=models.BooleanField(default=False, null=True, verbose_name='List-like'),
        ),
    ]
